// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCse_O4THYUWO5gySwVuSOhZQtmpJ0v4p0',
    appId: '1:844570369533:web:e43d9c1774c8b64dad8d94',
    messagingSenderId: '844570369533',
    projectId: 'individual-assign-2',
    authDomain: 'individual-assign-2.firebaseapp.com',
    storageBucket: 'individual-assign-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4a_S7tcbbKQ25zccEgCoGPTdcbnwEOoQ',
    appId: '1:844570369533:android:61815f1aded73694ad8d94',
    messagingSenderId: '844570369533',
    projectId: 'individual-assign-2',
    storageBucket: 'individual-assign-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3dk7J0WeZk2-Ufy_WDAvnayGNaSosSs',
    appId: '1:844570369533:ios:a4630df1b841297cad8d94',
    messagingSenderId: '844570369533',
    projectId: 'individual-assign-2',
    storageBucket: 'individual-assign-2.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCse_O4THYUWO5gySwVuSOhZQtmpJ0v4p0',
    appId: '1:844570369533:web:92e5081f181fbae7ad8d94',
    messagingSenderId: '844570369533',
    projectId: 'individual-assign-2',
    authDomain: 'individual-assign-2.firebaseapp.com',
    storageBucket: 'individual-assign-2.firebasestorage.app',
  );
}
